spring.application.name=Hospital_patient_record_system
spring.datasource.url=jdbc:mysql://localhost:3306/hospital
spring.datasource.username= root
spring.datasource.password=parimal@2304
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
