spring.datasource.url=Your_url #jdbc:mysql://localhost:3306/database_name
spring.datasource.username=Your_root
spring.datasource.password=Your_password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true